//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchRecord.Infraestructure.Constants {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageConstants() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchRecord.Infraestructure.Constants.MessageConstants", typeof(MessageConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///       [dbo].[XiruxEncript]
        ///       (@IdUsuario, @Password, 1) contrasena.
        /// </summary>
        internal static string DesencriptarPassword {
            get {
                return ResourceManager.GetString("DesencriptarPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT LTRIM(RTRIM(CentroCosto)) AS CentroCosto, IdCenCos
        /// AS IdCenCos
        ///FROM [dbo].[VWGDBIFactSales]
        ///ORDER BY CentroCosto.
        /// </summary>
        internal static string GetCostCenterOfVentas {
            get {
                return ResourceManager.GetString("GetCostCenterOfVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    EU.[IdUsuari], 
        ///    EU.[UsuPassword],
        ///    EU.[IdEmpresa], 
        ///    EU.[UsuDirActivo],
        ///    EUA.[Defecto],
        ///    EL.[IdEmpresaLogica],
        ///    EL.[NomEmpresaLogica]
        ///FROM EmpUsuarios EU
        ///INNER JOIN EmpUsuAutori EUA ON EUA.[IdUsuari] = EU.[UsuDirActivo]
        ///INNER JOIN EmpLogica EL ON EL.[IdEmpresa] = EUA.[IdEmpresa]  and EL.[IdEmpresaLogica] = EUA.[EmpLogica]
        ///WHERE EU.IdUsuari = @idUsuario.
        /// </summary>
        internal static string GetEmpUsuarios {
            get {
                return ResourceManager.GetString("GetEmpUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT a.[IdObjeto], a.[IdUsuari], a.[NivelA], c.IdCtrl,c.VisCtrl,c.HabCtrl
        ///FROM [dbo].[GenAutori] as a
        ///left join GenAutCtrl as c on c.IdObjeto = a.IdObjeto and a.IdUsuari = c.IdUsuari
        ///WHERE a.IdObjeto = @IdObjeto AND a.IdUsuari = @IdUsuario.
        /// </summary>
        internal static string GetPermisos {
            get {
                return ResourceManager.GetString("GetPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a   SELECT 
        ///    YEAR(FecContab) AS year,
        ///    MONTH(FecContab) AS Mes,
        ///    IdCenCos,
        ///    CentroCosto,
        ///    SUM(Cantidad) AS totalCantidadPorMes,
        ///    SUM(Cantidad * VrUnitKardex - VrDesc) AS valornetoPorMes
        ///FROM [dbo].[VWGDBIFactSales]
        ///WHERE YEAR(FecContab) = @year
        ///  AND IdCenCos IN @costCenter
        ///GROUP BY 
        ///    YEAR(FecContab),
        ///    MONTH(FecContab),
        ///    IdCenCos,
        ///    CentroCosto
        ///ORDER BY 
        ///    year,
        ///    Mes;.
        /// </summary>
        internal static string GetVentas {
            get {
                return ResourceManager.GetString("GetVentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT DISTINCT YEAR(FecContab) as FecContab
        ///FROM [dbo].[VWGDBIFactSales] 
        ///ORDER BY YEAR(FecContab).
        /// </summary>
        internal static string GetYearsOfVentas {
            get {
                return ResourceManager.GetString("GetYearsOfVentas", resourceCulture);
            }
        }
    }
}
